-- Table: public.Books

-- DROP TABLE IF EXISTS public."Books";

CREATE TABLE IF NOT EXISTS public."Books"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default",
    author text COLLATE pg_catalog."default",
    year integer,
    CONSTRAINT "Books_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Books"
    OWNER to postgres;